import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { FiArrowLeft, FiArrowRight, FiFileText, FiImage, FiPlus } from "react-icons/fi";
import { completeSalesVendorRegistration } from "../../services/api";
import { clearVendorRegistrationDraft, defaultServices, experienceOptions, readDraft, saveDraft, STEP1_KEY, STEP2_KEY, STEP3_KEY } from "./vendorRegistrationUtils";
import "./VendorRegistration.css";

const MAX=5*1024*1024;
export default function VendorRegistrationStep3(){
 const navigate=useNavigate(),step1=readDraft(STEP1_KEY),step2=readDraft(STEP2_KEY);
 const saved=readDraft(STEP3_KEY,{aboutBusiness:"",experience:"",services:[],minPrice:"",maxPrice:"",openingTime:"",closingTime:"",privacyAccepted:false,termsAccepted:false});
 const [form,setForm]=useState(saved),[logo,setLogo]=useState(null),[preview,setPreview]=useState(""),[custom,setCustom]=useState(""),[documents,setDocuments]=useState({}),[error,setError]=useState(""),[submitting,setSubmitting]=useState(false);
 useEffect(()=>{if(!step1)navigate("/vendor-registration",{replace:true});else if(!step2)navigate("/vendor-registration/contact",{replace:true});},[navigate,step1,step2]);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
 const selected=useMemo(()=>new Set(form.services),[form.services]);
 if(!step1||!step2)return null;
 const file=(name,f)=>{if(!f)return;if(f.size>MAX)return setError(`${f.name} exceeds 5 MB.`);if(name==="logo"&&!['image/jpeg','image/png'].includes(f.type))return setError("Logo must be JPG or PNG.");setError("");if(name==="logo"){if(preview)URL.revokeObjectURL(preview);setLogo(f);setPreview(URL.createObjectURL(f));}else setDocuments(p=>({...p,[name]:f}));};
 const toggle=s=>setForm(p=>({...p,services:selected.has(s)?p.services.filter(x=>x!==s):[...p.services,s]}));
 const addCustom=()=>{const s=custom.trim();if(s&&!selected.has(s))setForm(p=>({...p,services:[...p.services,s]}));setCustom("");};
 const save=()=>{saveDraft(STEP3_KEY,form);setError("Progress saved on this device. Files must be selected again after leaving the page.");};
 const submit=async(e)=>{e.preventDefault();setError("");const min=Number(form.minPrice),max=Number(form.maxPrice);if(form.aboutBusiness.trim().length<20)return setError("Describe the business in at least 20 characters.");if(!form.experience)return setError("Select years of experience.");if(!form.services.length)return setError("Select at least one service.");if(!Number.isFinite(min)||min<0||!Number.isFinite(max)||max<min)return setError("Enter a valid pricing range.");if(!form.openingTime||!form.closingTime||form.openingTime===form.closingTime)return setError("Enter valid opening and closing times.");if(!form.privacyAccepted||!form.termsAccepted)return setError("Accept the Privacy Policy and Terms & Conditions.");try{setSubmitting(true);const body=new FormData();body.append("registration",JSON.stringify({step1,step2,step3:{...form,aboutBusiness:form.aboutBusiness.trim(),minPrice:min,maxPrice:max}}));if(logo)body.append("logo",logo);Object.entries(documents).forEach(([k,v])=>body.append(k,v));const response=await completeSalesVendorRegistration(body);clearVendorRegistrationDraft();navigate("/vendors",{replace:true,state:{message:response?.message||"Vendor registration completed.",vendorId:response?.data?.vendorId}});}catch(x){setError(x?.message||"Registration could not be completed.");}finally{setSubmitting(false);}};
 const docRow=(name,label)=><label className="vr-doc-row"><FiFileText/><span>{documents[name]?.name||label}</span><em>{documents[name]?"Change":"Browse"}</em><input type="file" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" onChange={e=>file(name,e.target.files?.[0])}/></label>;
 return <main className="vr-page"><section className="vr-frame"><header className="vr-header"><button className="vr-back" onClick={()=>navigate("/vendor-registration/contact")}><FiArrowLeft/></button><h1>Vendor Registration</h1><span className="vr-step-small">Step 3 of<br/>3</span></header><div className="vr-content"><div className="vr-progress-label"><span>Step 3 of 3</span><span>Business Details</span></div><div className="vr-progress"><span style={{width:"100%"}}/></div><form className="vr-card" onSubmit={submit}><h2 className="vr-section-title">Business Details &amp; Services</h2><p className="vr-section-copy">Tell us more about what you offer to complete the vendor profile.</p>
 <label className="vr-field">Profile Photo / Logo<div className="vr-upload">{preview?<img className="vr-preview" src={preview} alt="Logo preview"/>:<><span className="vr-upload-icon"><FiImage/></span><strong>Drag and drop your logo here, or click to browse.</strong><small>JPG, PNG up to 5 MB</small></>}<input type="file" accept="image/jpeg,image/png" onChange={e=>file("logo",e.target.files?.[0])}/></div></label>
 <label className="vr-field">About the Business<textarea value={form.aboutBusiness} onChange={e=>setForm({...form,aboutBusiness:e.target.value})} placeholder="Describe your expertise, mission, and what makes your service unique..." maxLength={1000}/></label>
 <label className="vr-field">Years of Experience<select value={form.experience} onChange={e=>setForm({...form,experience:e.target.value})}><option value="">Select years in business</option>{experienceOptions.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label>
 <label className="vr-field">Services Offered<div className="vr-chips">{[...defaultServices,...form.services.filter(s=>!defaultServices.includes(s))].map(s=><button type="button" key={s} className={`vr-chip ${selected.has(s)?"active":""}`} onClick={()=>toggle(s)}>{s}</button>)}</div><div className="vr-custom"><input value={custom} onChange={e=>setCustom(e.target.value)} placeholder="Custom service"/><button type="button" onClick={addCustom}><FiPlus/> Add Custom</button></div></label>
 <h3 className="vr-subtitle">Pricing Details</h3><p className="vr-section-copy">Set a general price range for your services.</p><div className="vr-grid"><label className="vr-field">Min Price (₹)<input type="number" min="0" value={form.minPrice} onChange={e=>setForm({...form,minPrice:e.target.value})} placeholder="0.00"/></label><label className="vr-field">Max Price (₹)<input type="number" min="0" value={form.maxPrice} onChange={e=>setForm({...form,maxPrice:e.target.value})} placeholder="0.00"/></label></div>
 <h3 className="vr-subtitle">Business Hours</h3><div className="vr-grid"><label className="vr-field">Opening Time<input type="time" value={form.openingTime} onChange={e=>setForm({...form,openingTime:e.target.value})}/></label><label className="vr-field">Closing Time<input type="time" value={form.closingTime} onChange={e=>setForm({...form,closingTime:e.target.value})}/></label></div>
 <h3 className="vr-subtitle">Business Verification Documents</h3><p className="vr-section-copy">Upload relevant documents to verify the business. PDF, JPG or PNG, up to 5 MB each.</p>{docRow("gstCertificate","GST Certificate")}{docRow("msmeCertificate","MSME Certificate")}{docRow("identityProof","Other / Misc Document")}
 <div className="vr-consents"><label className="vr-consent"><input type="checkbox" checked={form.privacyAccepted} onChange={e=>setForm({...form,privacyAccepted:e.target.checked})}/>I agree to the Privacy Policy</label><label className="vr-consent"><input type="checkbox" checked={form.termsAccepted} onChange={e=>setForm({...form,termsAccepted:e.target.checked})}/>I agree to the Terms &amp; Conditions</label></div>
 {error&&<div className="vr-message">{error}</div>}<div className="vr-actions"><button type="button" className="vr-secondary" onClick={save}>Save for later</button><button className="vr-primary" disabled={submitting}>{submitting?"Registering...":"Complete Registration"}<FiArrowRight/></button></div></form></div></section></main>;
}
