import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { FiArrowLeft, FiArrowRight } from "react-icons/fi";
import { digitsOnly, readDraft, saveDraft, STEP1_KEY, STEP2_KEY } from "./vendorRegistrationUtils";
import "./VendorRegistration.css";

export default function VendorRegistrationStep2(){
 const navigate=useNavigate();const step1=readDraft(STEP1_KEY);
 const [form,setForm]=useState(()=>readDraft(STEP2_KEY,{whatsapp:"",sameAsMobile:false,email:"",address:"",city:"",state:"",landmark:""}));const [errors,setErrors]=useState({});
 useEffect(()=>{if(!step1)navigate("/vendor-registration",{replace:true});},[navigate,step1]);
 if(!step1)return null;
 const change=(name,value)=>{setForm(p=>({...p,[name]:value}));setErrors(p=>({...p,[name]:""}));};
 const same=(checked)=>setForm(p=>({...p,sameAsMobile:checked,whatsapp:checked?step1.mobileNumber:""}));
 const next=(e)=>{e.preventDefault();const x={};if(!/^[6-9]\d{9}$/.test(form.whatsapp))x.whatsapp="Enter a valid WhatsApp number.";if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email.trim()))x.email="Enter a valid email address.";if(form.address.trim().length<5)x.address="Enter the full street address.";if(form.city.trim().length<2)x.city="Enter the city.";if(form.state.trim().length<2)x.state="Enter the state or region.";setErrors(x);if(Object.keys(x).length)return;saveDraft(STEP2_KEY,{...form,email:form.email.trim().toLowerCase(),address:form.address.trim(),city:form.city.trim(),state:form.state.trim(),landmark:form.landmark.trim()});navigate("/vendor-registration/details");};
 return <main className="vr-page"><section className="vr-frame"><header className="vr-header"><button className="vr-back" onClick={()=>navigate("/vendor-registration")}><FiArrowLeft/></button><h1>Vendor Registration</h1><span/></header><div className="vr-content"><div className="vr-progress-label"><span>Step 2 of 3</span><span>Contact &amp; Location</span></div><div className="vr-progress"><span style={{width:"66.666%"}}/></div><form onSubmit={next}>
 <section className="vr-card vr-contact-card"><h2 className="vr-section-title">Contact Information</h2><label className={`vr-field ${errors.whatsapp?"invalid":""}`}>WhatsApp Number<div className="vr-phone"><span>+91</span><input value={form.whatsapp} onChange={e=>change("whatsapp",digitsOnly(e.target.value,10))} inputMode="numeric" placeholder="9876543210"/></div>{errors.whatsapp&&<small className="vr-error">{errors.whatsapp}</small>}</label><label className="vr-check"><input type="checkbox" checked={form.sameAsMobile} onChange={e=>same(e.target.checked)}/>Same as mobile number from Step 1</label><label className={`vr-field ${errors.email?"invalid":""}`}>Email Address<input type="email" value={form.email} onChange={e=>change("email",e.target.value)} placeholder="vendor@example.com"/>{errors.email&&<small className="vr-error">{errors.email}</small>}</label></section>
 <section className="vr-card"><h2 className="vr-section-title">Location Details</h2><label className={`vr-field ${errors.address?"invalid":""}`}>Full Street Address<input value={form.address} onChange={e=>change("address",e.target.value)} placeholder="123 Business Parkway, Suite 100" maxLength={255}/>{errors.address&&<small className="vr-error">{errors.address}</small>}</label><label className={`vr-field ${errors.city?"invalid":""}`}>City<input value={form.city} onChange={e=>change("city",e.target.value)} placeholder="Hyderabad" maxLength={100}/>{errors.city&&<small className="vr-error">{errors.city}</small>}</label><label className={`vr-field ${errors.state?"invalid":""}`}>State / Region<input value={form.state} onChange={e=>change("state",e.target.value)} placeholder="Telangana" maxLength={100}/>{errors.state&&<small className="vr-error">{errors.state}</small>}</label><label className="vr-field">Landmark <small style={{float:"right",fontWeight:400}}>Optional</small><input value={form.landmark} onChange={e=>change("landmark",e.target.value)} placeholder="Near the central plaza" maxLength={255}/></label></section>
 <div className="vr-actions"><button className="vr-primary">Next Step <FiArrowRight/></button></div></form></div></section></main>;
}
